[package]
name = "plat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
dialoguer = "0.11.0"
colored = "2.1.0"
fs_extra = "1.3.0"
indicatif = "0.17.8"
glob = "0.3.1"